name: pytorch-lightning-base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch-lightning
  - cudatoolkit=11.6
  - cudnn
  - scipy
  - jupyterlab
  - ipywidgets
  - torchmetrics
  - python
  - tensorboard
  - scikit-learn
  - matplotlib
  - pytorch=1.12.1
  - numpy
  - seaborn